// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axsakttnbpbdnjyifwbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4c2FrdHRuYnBiZG5qeWlmd2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNzgxOTIsImV4cCI6MjA1ODg1NDE5Mn0.ZbnPRgCpbp6zzmtzTOnuxihVVdnlZj9vxd8byma0MRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);